In [1]:
#!/usr/bin/python3
# coding: utf-8

import sys
import json
import requests
import time
import csv
from datetime import date, timedelta
#import mysql.connector
from json import JSONDecoder
# import xlsxwriter
import os

import pandas as pd
from pandas import ExcelWriter
import numpy as np
from bs4 import BeautifulSoup
from os.path import basename
import datetime

In [2]:
import calendar
import numpy as np
calendar.setfirstweekday(6)

def get_week_of_month(year, month, day):
    x = np.array(calendar.monthcalendar(year, month))
    week_of_month = np.where(x==day)[0][0] + 1
    return(week_of_month)

In [3]:
from datetime import date
from datetime import timedelta
today = date.today() # or you can do today = date.today() for today's date

for i in range(1,8):
    excel_date = today - timedelta(days=i)
    print(excel_date)
#     stored_file_location = "/root/PRTG_DAILY_REPORT/weekly_report_gp/"
    excel_name_old = str(excel_date) + "-18-00-00-all-site-report-prtg-dhaka-peak.xlsx"

2022-11-02
2022-11-01
2022-10-31
2022-10-30
2022-10-29
2022-10-28
2022-10-27

In [4]:
# For older data

# from datetime import date
# from datetime import timedelta
# today = date.today() # or you can do today = date.today() for today's date

# # for i in range(1,8):
# for i in range(4,11):
#     excel_date = today - timedelta(days=i)
#     print(excel_date)
# #     stored_file_location = "/root/PRTG_DAILY_REPORT/weekly_report_gp/"
#     excel_name_old = str(excel_date) + "-18-00-00-all-site-report-prtg-dhaka-peak.xlsx"

In [5]:
from datetime import date
from datetime import timedelta
today = date.today() # or you can do today = date.today() for today's date

for i in range(1,8):
    excel_date = today - timedelta(days=i)
    print(excel_date)
#     stored_file_location = "/root/PRTG_DAILY_REPORT/weekly_report_gp/"
    excel_name_old = str(excel_date) + "-18-00-00-all-site-report-prtg-dhaka-peak.xlsx"
    
#     # check eligibility
    if i == 1:
        dat1 =  pd.read_excel(excel_name_old, index_col=0)  
        dat1["Eligible"] = "NO"
        excel_name_last =  str(excel_date) + "-18-00-00-all-site-report-prtg-dhaka-peak.xlsx"
        excel_name_pd_last = pd.read_excel(excel_name_last, index_col=0)
        dat1["count"] = 0
        
        dat1 = dat1.set_index('site_name')
        dat1 = dat1.loc[~dat1.index.duplicated(keep='first')]
        
        
        
        
        
    else:
        
        excel_name_pd = pd.read_excel(excel_name_old, index_col=0)
        excel_name_pd = excel_name_pd.drop(columns=["capacity_Mbps","count","Eligible","Starting Date","Peak"])
        excel_name_pd = excel_name_pd.set_index('site_name')
        excel_name_pd = excel_name_pd.loc[~excel_name_pd.index.duplicated(keep='first')]
        
        dat1 = pd.concat([dat1, excel_name_pd], axis=1, join="inner")
#         result = pd.concat([df1, df2], axis=1, join="inner")

2022-11-02
2022-11-01
2022-10-31
2022-10-30
2022-10-29
2022-10-28
2022-10-27

In [6]:
# For older data


# from datetime import date
# from datetime import timedelta
# today = date.today() # or you can do today = date.today() for today's date

# # for i in range(1,8):
# for i in range(4,11):
#     excel_date = today - timedelta(days=i)
#     print(excel_date)
# #     stored_file_location = "/root/PRTG_DAILY_REPORT/weekly_report_gp/"
#     excel_name_old = str(excel_date) + "-18-00-00-all-site-report-prtg-dhaka-peak.xlsx"
    
# #     # check eligibility
#     if i == 4:
#         dat1 =  pd.read_excel(excel_name_old, index_col=0)  
#         dat1["Eligible"] = "NO"
#         excel_name_last =  str(excel_date) + "-18-00-00-all-site-report-prtg-dhaka-peak.xlsx"
#         excel_name_pd_last = pd.read_excel(excel_name_last, index_col=0)
#         dat1["count"] = 0
        
#         dat1 = dat1.set_index('site_name')
#         dat1 = dat1.loc[~dat1.index.duplicated(keep='first')]
        
        
        
        
        
#     else:
        
#         excel_name_pd = pd.read_excel(excel_name_old, index_col=0)
#         excel_name_pd = excel_name_pd.drop(columns=["capacity_Mbps","count","Eligible","Starting Date","Peak"])
#         excel_name_pd = excel_name_pd.set_index('site_name')
#         excel_name_pd = excel_name_pd.loc[~excel_name_pd.index.duplicated(keep='first')]
        
#         dat1 = pd.concat([dat1, excel_name_pd], axis=1, join="inner")
# #         result = pd.concat([df1, df2], axis=1, join="inner")

In [7]:
dat1

,capacity_Mbps,count,Eligible,Starting Date,Peak,11/2/2022 12:00:00 AM - 12:05:00 AM,11/2/2022 12:05:00 AM - 12:10:00 AM,11/2/2022 12:10:00 AM - 12:15:00 AM,11/2/2022 12:15:00 AM - 12:20:00 AM,11/2/2022 12:20:00 AM - 12:25:00 AM,...,10/27/2022 11:10:00 PM - 11:15:00 PM,10/27/2022 11:15:00 PM - 11:20:00 PM,10/27/2022 11:20:00 PM - 11:25:00 PM,10/27/2022 11:25:00 PM - 11:30:00 PM,10/27/2022 11:30:00 PM - 11:35:00 PM,10/27/2022 11:35:00 PM - 11:40:00 PM,10/27/2022 11:40:00 PM - 11:45:00 PM,10/27/2022 11:45:00 PM - 11:50:00 PM,10/27/2022 11:50:00 PM - 11:55:00 PM,10/27/2022 11:55:00 PM - 12:00:00 AM
site_name,,,,,,,,,,,,,,,,,,,,,
DHACAI,100,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,39.546875,0.242188,0.677734,0.183594,0.398438,0.341797,...,0.230469,0.201172,0.218750,0.236328,0.191406,0.188477,0.184570,0.186523,0.180664,0.175781
DHADB5,100,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,82.672852,64.392578,69.375000,57.352539,70.755859,63.063477,...,71.817383,68.140625,70.158203,56.042969,48.821289,63.865234,62.722656,62.059570,61.956055,68.325195
DHADBI,100,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,9.518555,1.106445,1.061523,0.555664,0.384766,0.150391,...,1.012695,0.256836,0.223633,0.190430,0.777344,0.913086,1.547852,2.816406,1.987305,1.737305
DHAGHI,100,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,35.684570,4.196289,9.918945,7.237305,9.477539,8.883789,...,7.301758,7.999023,11.644531,13.946289,15.518555,14.919922,8.171875,9.689453,9.327148,11.516602
DHAKHI,100,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,30.507812,0.595703,1.305664,1.548828,2.540039,1.783203,...,6.838867,4.833008,2.195312,1.941406,1.352539,0.860352,1.738281,0.983398,0.700195,1.204102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SYTUK1,350,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,371.348633,328.917969,304.155273,308.856445,308.257812,311.343750,...,321.220703,319.452148,316.386719,316.070312,298.194336,313.934570,308.166016,314.972656,313.882812,328.531250
SYUPS6,350,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,271.400391,271.353516,271.400391,262.622070,244.383789,239.501953,...,226.321289,254.560547,251.931641,253.486328,256.001953,243.920898,229.977539,228.461914,239.701172,249.532227
TGRSK3,200,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,39.214844,30.289062,33.425781,33.238281,30.641602,29.213867,...,38.241211,40.832031,41.180664,39.005859,35.974609,34.015625,35.758789,30.070312,36.518555,39.548828
TNGTLB,200,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,76.544922,51.240234,56.179688,37.677734,37.701172,51.196289,...,50.454102,50.861328,60.583984,80.144531,52.672852,48.547852,47.402344,45.401367,45.526367,42.939453
TNKRA1,200,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,25.083008,3.246094,5.150391,2.429688,3.051758,3.616211,...,16.337891,12.330078,14.243164,12.848633,16.349609,13.181641,8.450195,7.937500,9.278320,6.912109

In [8]:
dat1=dat1.reset_index()

In [9]:
dat1

,site_name,capacity_Mbps,count,Eligible,Starting Date,Peak,11/2/2022 12:00:00 AM - 12:05:00 AM,11/2/2022 12:05:00 AM - 12:10:00 AM,11/2/2022 12:10:00 AM - 12:15:00 AM,11/2/2022 12:15:00 AM - 12:20:00 AM,...,10/27/2022 11:10:00 PM - 11:15:00 PM,10/27/2022 11:15:00 PM - 11:20:00 PM,10/27/2022 11:20:00 PM - 11:25:00 PM,10/27/2022 11:25:00 PM - 11:30:00 PM,10/27/2022 11:30:00 PM - 11:35:00 PM,10/27/2022 11:35:00 PM - 11:40:00 PM,10/27/2022 11:40:00 PM - 11:45:00 PM,10/27/2022 11:45:00 PM - 11:50:00 PM,10/27/2022 11:50:00 PM - 11:55:00 PM,10/27/2022 11:55:00 PM - 12:00:00 AM
0,DHACAI,100,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,39.546875,0.242188,0.677734,0.183594,0.398438,...,0.230469,0.201172,0.218750,0.236328,0.191406,0.188477,0.184570,0.186523,0.180664,0.175781
1,DHADB5,100,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,82.672852,64.392578,69.375000,57.352539,70.755859,...,71.817383,68.140625,70.158203,56.042969,48.821289,63.865234,62.722656,62.059570,61.956055,68.325195
2,DHADBI,100,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,9.518555,1.106445,1.061523,0.555664,0.384766,...,1.012695,0.256836,0.223633,0.190430,0.777344,0.913086,1.547852,2.816406,1.987305,1.737305
3,DHAGHI,100,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,35.684570,4.196289,9.918945,7.237305,9.477539,...,7.301758,7.999023,11.644531,13.946289,15.518555,14.919922,8.171875,9.689453,9.327148,11.516602
4,DHAKHI,100,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,30.507812,0.595703,1.305664,1.548828,2.540039,...,6.838867,4.833008,2.195312,1.941406,1.352539,0.860352,1.738281,0.983398,0.700195,1.204102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,SYTUK1,350,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,371.348633,328.917969,304.155273,308.856445,308.257812,...,321.220703,319.452148,316.386719,316.070312,298.194336,313.934570,308.166016,314.972656,313.882812,328.531250
1457,SYUPS6,350,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,271.400391,271.353516,271.400391,262.622070,244.383789,...,226.321289,254.560547,251.931641,253.486328,256.001953,243.920898,229.977539,228.461914,239.701172,249.532227
1458,TGRSK3,200,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,39.214844,30.289062,33.425781,33.238281,30.641602,...,38.241211,40.832031,41.180664,39.005859,35.974609,34.015625,35.758789,30.070312,36.518555,39.548828
1459,TNGTLB,200,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,76.544922,51.240234,56.179688,37.677734,37.701172,...,50.454102,50.861328,60.583984,80.144531,52.672852,48.547852,47.402344,45.401367,45.526367,42.939453
1460,TNKRA1,200,0,NO,11/2/2022 12:00:00 AM - 12:05:00 AM,25.083008,3.246094,5.150391,2.429688,3.051758,...,16.337891,12.330078,14.243164,12.848633,16.349609,13.181641,8.450195,7.937500,9.278320,6.912109

In [10]:
lists = dat1.columns.to_list()
cols = lists[6:]

In [11]:
# Getting the capacity
df_count = dat1['capacity_Mbps'].to_list()
dat1['count'] = dat1[cols].gt(df_count, axis='index').sum(axis=1)

In [12]:
dat1['Peak'] = dat1[cols].max(axis=1)

In [13]:
dat1.loc[dat1['count'] > 84, 'Eligible'] = 'YES'

In [14]:
dat_first_exced = dat1[cols].gt(df_count, axis='index').dot(dat1[cols].columns + ',').str[:-1].str.rsplit(',', 1)

In [15]:
sheet2 = dat1.loc[dat1['Eligible'] == "YES"]

In [16]:
sheet2_3 = sheet2[['site_name', 'capacity_Mbps', 'count', 'Peak']].copy()

In [17]:
sheet2_3

     site_name  capacity_Mbps  count        Peak
20      DHBAB3            100    135  116.928711
380     DHMOTA            100    161  150.443359
858     CXRMUM            200   1125  311.594727
876     DHKMPG            100    361  117.620117
890     DHSAVQ            200    191  258.473633
1021    SNGBG1            200   1219  317.100586
1023    SNJAW3            200   1073  310.287109
1028    SNMIR1            200    193  228.296875
1044    SYBBD1            200    724  287.351562
1045    SYBIA3            200    407  241.955078
1150    BMBID1            500    151  617.758789
1282    DHSAVA            200    654  302.423828
1286    DHZAOI            100    417  117.990234
1406    NSCSD4            200    156  234.694336

In [18]:
dat1['first_exceed'] = str('--')

In [19]:
for index, row in sheet2_3.iterrows():
#     print(index)
#     print(dat_first_exced.iloc[index][1])
    data = dat_first_exced.iloc[index][1]
    dat1.iloc[index, dat1.columns.get_loc('first_exceed')] = data

In [20]:
sheet2__st = dat1.loc[dat1['Eligible'] == "YES"]

In [21]:
sheet2__st

,site_name,capacity_Mbps,count,Eligible,Starting Date,Peak,11/2/2022 12:00:00 AM - 12:05:00 AM,11/2/2022 12:05:00 AM - 12:10:00 AM,11/2/2022 12:10:00 AM - 12:15:00 AM,11/2/2022 12:15:00 AM - 12:20:00 AM,...,10/27/2022 11:15:00 PM - 11:20:00 PM,10/27/2022 11:20:00 PM - 11:25:00 PM,10/27/2022 11:25:00 PM - 11:30:00 PM,10/27/2022 11:30:00 PM - 11:35:00 PM,10/27/2022 11:35:00 PM - 11:40:00 PM,10/27/2022 11:40:00 PM - 11:45:00 PM,10/27/2022 11:45:00 PM - 11:50:00 PM,10/27/2022 11:50:00 PM - 11:55:00 PM,10/27/2022 11:55:00 PM - 12:00:00 AM,first_exceed
20,DHBAB3,100,135,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,116.928711,65.642578,65.835938,76.250000,66.293945,...,51.136719,52.653320,50.087891,62.950195,69.504883,68.717773,63.204102,71.572266,72.060547,10/27/2022 5:55:00 PM - 6:00:00 PM
380,DHMOTA,100,161,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,150.443359,21.067383,29.090820,21.447266,23.025391,...,25.961914,27.343750,28.185547,32.187500,36.994141,33.032227,23.591797,20.462891,20.286133,10/27/2022 8:35:00 PM - 8:40:00 PM
858,CXRMUM,200,1125,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,311.594727,155.446289,152.280273,143.001953,151.447266,...,259.916992,258.054688,245.674805,241.826172,239.108398,232.804688,218.175781,244.387695,230.916016,10/27/2022 11:55:00 PM - 12:00:00 AM
876,DHKMPG,100,361,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,117.620117,111.897461,109.615234,103.482422,108.938477,...,114.816406,115.756836,115.512695,106.774414,117.060547,115.892578,117.115234,116.452148,109.702148,10/27/2022 11:55:00 PM - 12:00:00 AM
890,DHSAVQ,200,191,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,258.473633,216.164062,215.695312,202.971680,212.783203,...,228.859375,213.123047,195.812500,197.813477,199.860352,207.223633,195.308594,186.098633,185.302734,10/27/2022 11:40:00 PM - 11:45:00 PM
1021,SNGBG1,200,1219,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,317.100586,228.272461,233.837891,251.825195,245.797852,...,250.715820,244.935547,258.944336,256.075195,229.558594,230.469727,235.538086,230.337891,237.626953,10/27/2022 11:55:00 PM - 12:00:00 AM
1023,SNJAW3,200,1073,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,310.287109,213.732422,201.141602,201.223633,186.276367,...,280.434570,262.177734,259.468750,252.248047,257.236328,255.165039,241.841797,242.012695,243.223633,10/27/2022 11:55:00 PM - 12:00:00 AM
1028,SNMIR1,200,193,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,228.296875,199.875000,205.797852,197.221680,190.784180,...,205.711914,205.821289,204.906250,211.247070,203.726562,201.489258,194.373047,196.156250,189.276367,10/27/2022 11:40:00 PM - 11:45:00 PM
1044,SYBBD1,200,724,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,287.351562,248.732422,236.235352,245.653320,234.256836,...,263.453125,260.527344,259.134766,245.875000,247.336914,248.430664,250.661133,247.108398,251.164062,10/27/2022 11:55:00 PM - 12:00:00 AM
1045,SYBIA3,200,407,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,241.955078,224.118164,239.642578,229.002930,240.132812,...,214.252930,222.119141,218.654297,214.536133,220.141602,233.608398,233.499023,230.784180,241.955078,10/27/2022 11:55:00 PM - 12:00:00 AM
1150,BMBID1,500,151,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,617.758789,333.054688,315.312500,311.607422,293.307617,...,392.634766,382.729492,362.504883,357.901367,343.451172,351.990234,332.708984,336.677734,327.418945,10/27/2022 10:00:00 PM - 10:05:00 PM
1282,DHSAVA,200,654,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,302.423828,202.058594,202.049805,181.379883,162.294922,...,265.155273,281.070312,251.866211,204.688477,202.011719,210.119141,210.034180,200.371094,180.485352,10/27/2022 11:50:00 PM - 11:55:00 PM
1286,DHZAOI,100,417,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,117.990234,83.595703,70.907227,64.219727,71.143555,...,108.803711,100.816406,88.259766,101.430664,113.970703,114.696289,108.979492,109.791992,99.023438,10/27/2022 11:50:00 PM - 11:55:00 PM
1406,NSCSD4,200,156,YES,11/2/2022 12:00:00 AM - 12:05:00 AM,234.694336,97.081055,89.389648,82.390625,80.502930,...,130.065430,137.721680,126.803711,112.425781,119.148438,120.442383,106.860352,98.436523,98.464844,10/28/2022 10:05:00 PM - 10:10:00 PM

In [22]:
sheet2_1 = sheet2[['site_name', 'capacity_Mbps', 'count', 'Peak']].copy()

In [23]:
total_over_utilization_weekly = len(sheet2_1.index)

In [24]:
day_number = str(today.day)
month_number = str(today.month)
Year = str(today.year)
week_number = str(get_week_of_month(int(Year),int(month_number),int(day_number)))
mydate = datetime.datetime.now()
month_name = mydate.strftime("%B")

In [25]:
csv_name_all_excel = month_name+"-Week-" + week_number +"-" + Year +'-all-site' + "-report-prtg-GP.xlsx"
writer = ExcelWriter(csv_name_all_excel)
dat1.to_excel(writer,'Sheet 1')
sheet2_1.to_excel(writer,'Sheet 2')
writer.save()